### ISSUE TITLE
Throw error when add query

### ISSUE THREAD

**Issue by WangLarry** [mui/mui-toolpad#1001]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Click 'ADD QUERY' in right panel to add query In page, then show 'Create Query' dialog, choice connection, click 'create query' button. It will throw error in console window: 
```
Error: Node "j2t3hpa" not found
   
    at __WEBPACK_DEFAULT_EXPORT__ (/..../mui-toolpad/packages/toolpad-app/.next/server/pages/api/data/[appId]/[version]/[queryId].js:373:74)
```

The problem may be: click 'create query' button will call appDom.addNode which do 'setNodeParent', but not save data to database. The main page editor window can not load this node from database when refreshing screen.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by bharatkashyap** [comment]
Thanks for creating this issue @WangLarry! Which connection did you choose when creating the query in this case?

**Comment by Janpot** [comment]
I think I see the problem. When you create the query node in the frontend, the canvas immediately starts rendering the query that you've added and  that initiates a runtime fetch. The dom hasn't had the chance to sync to the backend yet, so the backend doesn't have knowledge yet of this new node. It will show an error when trying to fetch the data.

I think the solution will:

1. creating a "preview" mode for the query nodes that instead of sending a queryId will send over the whole query node,  that way the backend can respond without needing to fetch it from the database. For deployed apps we will still keep the current behavior.
2. Only add the query to the dom after the user has had the chance to edit its properties.

**Comment by WangLarry** [comment]
@Janpot Yes. Your description is very clear.

**Comment by WangLarry** [comment]
fix:

QueryEditor.tsx
```typescript
export default function QueryEditor() {

  ...

  const handleCreated = React.useCallback(
    (node: appDom.QueryNode) => {
      domApi.addNode(node, page, 'queries');
      domApi.saveNode(node);  // <--------------- Added
      setDialogState({ nodeId: node.id });
    },
    [domApi, page],
  );

 ...
```
