### ISSUE TITLE
Decrease bundle size

### ISSUE THREAD

**Issue by WangLarry** [mui/mui-toolpad#1008]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I use @next/bundle-analyzer to analyze toolpad-app. It show there are two huge packages: monaco-editor and @mui/icons-material.

<img width="1789" alt="截屏2022-09-15 19 19 08" src="https://user-images.githubusercontent.com/5869244/190394879-93bc21fe-6175-4815-ac3d-600059bf84c4.png">
<img width="593" alt="截屏2022-09-15 19 20 11" src="https://user-images.githubusercontent.com/5869244/190394906-b8122e88-77f0-46c4-afd7-02a1c879ea72.png">

**Comment by Janpot** [comment]
* `monaco-editor` is needed for the code editors. It's big because it contains a language server. It's in its own chunk and loaded asynchronously as a worker. I don't see a problem here.
* `@mui/icons-material` is also in its own chunk and lazy loaded on the deployed application but only if the user uses icons in custom scripts.

**Comment by WangLarry** [comment]
```
info  - Collecting page data  
Route (pages)                                Size     First Load JS
┌ λ /                                        1.16 kB         195 kB
├   /_app                                    0 B             119 kB
├ λ /_toolpad/[[...index]]                   330 kB         1.53 MB
├ λ /404                                     199 B           120 kB
├ λ /api/data/[appId]/[version]/[queryId]    0 B             119 kB
├ λ /api/dataSources/[dataSource]/[...path]  0 B             119 kB
├ λ /api/health-check                        0 B             119 kB
├ λ /api/rpc                                 0 B             119 kB
├ λ /app-canvas/[[...path]]                  2.92 kB         1.2 MB
├ λ /app/[appId]/[version]/[[...path]]       358 B           1.2 MB
└ λ /deploy/[appId]/[[...path]]              353 B           1.2 MB
+ First Load JS shared by all                119 kB
  ├ chunks/framework-2422bd4d7ba12811.js     45.9 kB
  ├ chunks/main-5b7e023216b20801.js          35 kB
  ├ chunks/pages/_app-5b8c0ac2d0c62fea.js    32 kB
  └ chunks/webpack-f2ca0da3ac4cec04.js       6.56 kB

ƒ Middleware                                 20.5 kB
```

**Comment by WangLarry** [comment]
http://localhost:3000/deploy/cl7q3tf6a0005px8cz8jbuij0/pages
<img width="1781" alt="截屏2022-09-15 23 04 39" src="https://user-images.githubusercontent.com/5869244/190439375-af4c6f1b-d77d-41f3-910f-ce8c51aa6829.png">


<img width="1539" alt="截屏2022-09-15 23 02 21" src="https://user-images.githubusercontent.com/5869244/190438946-8def8395-1a66-4f8c-84fd-b36d8a2fe0c2.png">

**Comment by Janpot** [comment]
@WangLarry Are there any specific problems you'd like to point out?

**Comment by Janpot** [comment]
> Can optimize load @mui/material/* module, using the method of dealing @mui/icons-material

I'm not sure that would work well with imports like:

```tsx
import Button, { buttonClasses } from "@mui/material/Button";
```

**Comment by WangLarry** [comment]
@Janpot 
```
      const compMatch = /^@mui\/material\/(.*)$/.exec(moduleId);
      if (compMatch) {
        const compName = compMatch[1];
        const compModule = modules.get('@mui/material');
        const compClasses = `${lowerCaseFirstLetter(compName)}Classes`;
        esModule = {
          default: (compModule as any)[compName],
          [compClasses]: (compModule as any)[compClasses],
        };
      }

    ....
    function lowerCaseFirstLetter(string: string) {
       return string.charAt(0).toLowerCase() + string.slice(1);
    }

```

**Comment by Janpot** [comment]
@WangLarry The point was that it requires us to hardcode the exports of each of those modules imported, which will be a maintenance burden as we'll have to keep it up to date as `@mui/material` evolves. So I don't feel like we should go that way. If the problem is the bundle splitting, we could organize the imports in a way that would create a chunk for all library code:

```tsx
// ./loadModule.ts

// ...
    const muiExports = await import('./muiExports')
// ...
```

```tsx
import muiMaterialDefault, * as muiMaterial from '@mui/material';
import muiMaterialAccordionDefault, * as muiMaterialAccordion from '@mui/material/Accordion';

function esm(defaultExport: any, namedExports: any) {
  return { ...namedExports, default: defaultExport, __esModule: true };
}

export default new Map([
  ['@mui/material', esm(muiMaterial, muiMaterialDefault)],
  ['@mui/material/Accordion', esm(muiMaterialAccordionDefault, muiMaterialAccordion)],
  // ...
]);
```

It's still not great as it still imports all library code, even when unused, but it will use less requests. It also hacks esm support on top of commonjs which will for sure run into edge cases at some point. In the future we could look into either a pure ESM runtime that only loads used components, or a serverside compilation step for deployed applications.
