### ISSUE TITLE
Show Alpha label at more places

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1251]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

MUI Toolpad also appears at the Footer of mui.com. A user can reach mui.com/toolpad from there and won't get to know that it is in alpha phase of development.

I suggest we put the label (the one we show on Products menu) at all such occurrences. 

<img width="625" alt="Screenshot 2022-10-31 at 4 31 39 PM" src="https://user-images.githubusercontent.com/92228082/198993441-5ba73b9a-5a5f-4af2-a5e4-aaf9d90412c3.png">

<img width="714" alt="Screenshot 2022-10-31 at 4 31 54 PM" src="https://user-images.githubusercontent.com/92228082/198993478-36decb28-4d1c-46a4-8e7d-f178ce4c606e.png">

<img width="376" alt="Screenshot 2022-10-31 at 4 32 34 PM" src="https://user-images.githubusercontent.com/92228082/198993596-c8a14568-fa76-4de0-807d-731fd2a43afb.png">

**Comment by gerdadesign** [comment]
## Footer
![Image](https://user-images.githubusercontent.com/106991024/200335511-70cd3a19-5016-49fd-a6df-4138c6f68892.jpg)
![Image](https://user-images.githubusercontent.com/106991024/200335512-5e71514f-5172-4b9a-bb99-15f39ae4491e.jpg)

## Logo
I adjusted the [logo variants in Figma](https://www.figma.com/file/nNAatyLlRl3Tq4nGHgAmNh/Branding-theme?node-id=6060%3A47809), so that the badge is an option you can turn on. Here's a screenshot of what that looks like in context of  both light and dark modes: 

![Image](https://user-images.githubusercontent.com/106991024/200336086-e07dc024-d2a4-46e9-8ae0-fa3ce6af3567.png)
![Image](https://user-images.githubusercontent.com/106991024/200336087-ba56427c-ada8-4f4c-b8a9-bd05450def0c.png)

## Docs
Should we also mimic the structure of Material UI and X in the docs with a version dropdown? Or does that not make sense for this product yet? 

![Image](https://user-images.githubusercontent.com/106991024/200336925-cb9ff8fd-f242-4c8a-8a3f-38d34f94c1c6.png)
![Image](https://user-images.githubusercontent.com/106991024/200336924-da45e559-2aad-44af-8571-c352a69450ef.png)

**Comment by prakhargupta1** [comment]
> Should we also mimic the structure of Material UI and X in the docs with a version dropdown? Or does that not make sense for this product yet?
Yes, makes sense to show alpha here as well.

We should also add label in the Toolpad app.

**Comment by bharatkashyap** [comment]
@gerdadesign Most large viewports don't have enough space to fit the label in the footer products list:

https://user-images.githubusercontent.com/19550456/202429003-64f458ab-5bcb-4db6-9844-737ccd839bcd.mov

Do you have any ideas around what to do here?
