### ISSUE TITLE
Deleting the custom component default code deletes the node.

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1421]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

https://user-images.githubusercontent.com/92228082/205879451-99ca0e57-cf55-4aa4-afe4-09d5d54641e1.mov

### Your environment 🌎

master toolpad

**Comment by apedroferreira** [comment]
+1
Even trying to change the name seems to cause the same issue.

**Comment by bytasv** [comment]
I've tried with a brand new component, same thing does not happen. Seems that it happens with that specific instance only (or at least couldn't find a way to reproduce in other place yet). Need to figure out if it's related to the data binding or something that could cause it 🤔 or maybe we can reproduce by importing DOM locally so that the error is more descriptive  (haven't tried it yet)

**Comment by Janpot** [comment]
I accidentally upgraded `react-router-dom` in https://github.com/mui/mui-toolpad/pull/1403/ even though I disabled it in renovatebot.

We're blocked on moving forward with this library on https://github.com/remix-run/react-router/issues/8139

Will fix.
