### ISSUE TITLE
How can i create custom component for datagrid cell?

### ISSUE THREAD

**Issue by yaredtsy** [mui/mui-toolpad#1595]
I am attempting to customize the appearance of a cell in a Datagrid by importing a custom component and changing the column type to 'codeComponent.' However, I am encountering an issue with utilizing the 'useGridApiContext' hook within the custom component.

![image](https://user-images.githubusercontent.com/34584266/214047945-8cf44b78-1063-4e97-9909-bdbf82e5473b.png)

Link: https://demo.toolpad.io/_toolpad/app/cld06iouh01jupc7byglpysen/pages/3a6l7cp4

**Comment by bytasv** [comment]
@yaredtsy - seems that the context is actually accessible when you look at the page where this component is rendered inside data grid.

@Janpot I'm not sure if we should/could do something inside Toolpad to make this work? i.e. trying to "guess" where this component could be used and then rendering it in the component preview on the right 🤔 
Alternatively maybe we should provide interface to define preview provide for each component so that user could define context that will be used?

I think at the current stage custom component code should be written "defensively", by checking whether it's even possible to access parent context and provide some defaults that would make this work in preview mode.

**Comment by Janpot** [comment]
@yaredtsy Interesting, that's clearly a limitation of using the custom component as a datagrid column renderer that we didn't foresee. As the sandbox we show the preview for custom components in is just a top-level react component, there is no DataGrid context there. Hence the reason why you see this error, yet, it renders without a problem in the actual datagrid. 

The way we intended this to work was as a pure component taking `field`, `value` and `row` props and rendering cell content for those (@bytasv this issue is a good indicator of something that we need to document). 

Could you explain a bit more the practical use-case you're looking for here? Perhaps we can come up with a solution that doesn't involve access to the `apiRef`? The only way I can see us solve this is if we somehow tie a code component to the datagrid we intend to render it into. Not sure how that would work exactly from a UX point of view, but good to be aware.

**Comment by yaredtsy** [comment]
> Could you explain a bit more the practical use-case you're looking for here

I am creating custom components to implement edit and delete actions in the Datagrid, as the toolpad does not have a built-in action type

How about providing a preview feature for the user, allowing them to view the page while editing the custom components?

![image](https://user-images.githubusercontent.com/34584266/214118203-15c2e9e8-e11d-48de-8123-68e5441be657.png)

**Comment by prakhargupta1** [comment]
@yaredtsy Toolpad has changed a lot lately. You can customize a data grid column as shown here: https://mui.com/toolpad/how-to-guides/customize-datagrid/
