### ISSUE TITLE
Add a .gitignore file to the .toolpad-generated folder

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1666]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Small task, summary not required.

**Comment by apedroferreira** [comment]
To clarify: should this `.gitignore` file be in the root of the application and include the `.toolpad-generated` folder so that that folder isn't checked out?
I took a look and this and how the direction-13 codebase works, and it feels like creating this type of file should be done along with the `init` command which we don't have yet.

**Comment by Janpot** [comment]
We can start by doing it in the init command. But eventually we will do this check as well every time we run `dev` on an existing project and make sure it's there

**Comment by apedroferreira** [comment]
Ok, if we should regenerate the files every time the user starts the project then I can add it already!
