### ISSUE TITLE
Example-2 (App to handle overdue invoices)

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1773]
Link to further details: https://www.notion.so/mui-org/Handle-orders-beyond-the-payment-terms-08d85f902da04f8bae315a2d2b54c369

We'll put the working app in https://github.com/mui/mui-private repo and a showcase version in: https://github.com/mui/mui-public

**Comment by bharatkashyap** [comment]
###  Thoughts from creating this overdue invoices app here

<details><summary><h3>Video</h3></summary>

https://user-images.githubusercontent.com/19550456/235036018-a6803db3-2cc8-4726-9621-051802e193ca.mov

</details>


<details><summary><h3>Delighted by:</h3></summary>

- `loading` on Markdown triggered when the underlying expression was loading, is this intentional and can this be done on all components?

 - Being able to write most of the code in my editor and then toggle to the screen to look at very quick mouse driven drag/drop UI feedback
    
 - Automatic column recalculation on Data Grids
</details> 
 
<details><summary><h3>Would be delighted by:</h3></summary>

- [ ]  Would have been great to be able to use the MySQL connection editor to test out SQL commands inside Toolpad

- [ ]  Would have been great to be able to import shared files inside the code components

- [ ]  Want to be able to describe dependent flows using a UI, instead of having to write multiple lines of code in the editor to describe things sequentially, such as
        
  ```js
  await query1.call() 
  await query2.refetch()
   ```
        
 - [ ] Editing code on screen
 
   - [ ]  Editing large markdown with template expressions inside the Modal editor is a pain. It’s fine if this is in browser, but something which is a bit more editor like would be better. Vertical?
   
   - [ ]  Same problem as above with editing binding expressions
   
- [ ]  If I could “select” values from the existing scope I want to bind to, for example, instead of having to type 
`textField.value`, if I could  click on this in the scope

</details> 
    

<details><summary><h3>Disappointed by:</h3></summary>

- [ ] Select components
    - [ ]  No `loading` on Select components
    - [ ]  Need an `onChange` handler on Select components
    
- [ ]  Not being able to see the components in a tree and instead having to click the correct area on the canvas

- [ ]  The Code Component errors must be more gracefully and discover-ably presented in the screen, instead of inside runtime errors or tooltips

- [ ]  There is little point in the bindings of the parameters of code queries if when manually calling them, those bound parameters are lost. We should honour those bindings when calling the query manually. 

- [ ] Actions
    - [ ]  Want to be able to directly bind queries instead of having to write `queryName.call()` in an editor on screen
    - [ ]  Want to run queries in succession, with one query being dependent on the outcome of the other, and describe actions in success/failure scenarios
    
</details>

**Comment by apedroferreira** [comment]
>  Not being able to see the components in a tree and instead having to click the correct area on the canvas

This should not be complicated to build (at least from the development side) and I also feel like it would be an important feature.

**Comment by prakhargupta1** [comment]
Completed in https://github.com/mui/mui-private/pull/294
