### ISSUE TITLE
datagrid not updating state on preview mode 

### ISSUE THREAD

**Issue by Prajapati-developer** [mui/mui-toolpad#1852]
![image](https://user-images.githubusercontent.com/128947562/229712303-3364f7d9-3b1f-4700-871c-dcb53d3980b3.png)
datagrid not updating state in preview mode as data is a async and taking time to populate 
@Janpot

**Comment by Prajapati-developer** [comment]
[toolpad.zip](https://github.com/mui/mui-toolpad/files/11148535/toolpad.zip)
here you can find that manually query is also not working in my case and in preview mode it is showing error state in data grid it is fine if i can show user friendly message. how can i navigate one page to another by using param on button click .
Thanks  in advance

**Comment by bharatkashyap** [comment]
@Prajapati-developer I think you might have missed adding all of the files in your project - I can only see one component file in the folder with a `CellRenderer` component inside it:

<img width="690" alt="Screenshot 2023-04-04 at 6 55 48 PM" src="https://user-images.githubusercontent.com/19550456/229961202-ceec462c-63ae-445a-8777-c94deadad4c1.png">

<img width="558" alt="Screenshot 2023-04-04 at 6 55 30 PM" src="https://user-images.githubusercontent.com/19550456/229961204-0884d275-3dd2-4532-a9cc-32fe33bfb03d.png">

Perhaps you could share a screenshot of the query which is not working for you

> how can i navigate one page to another by using param on button click 

If I understand correctly, you intent to navigate from one page to another while including params in the URL. This feature is being shaped and you can track its development in this issue https://github.com/mui/mui-toolpad/issues/1800

**Comment by Prajapati-developer** [comment]
[manage-user.zip](https://github.com/mui/mui-toolpad/files/11155230/manage-user.zip)
attached files here .

**Comment by bharatkashyap** [comment]
> [manage-user.zip](https://github.com/mui/mui-toolpad/files/11155230/manage-user.zip) attached files here .

Thanks @Prajapati-developer, the `usersList` query which the Datagrid was using to show data had a transformation enabled which was erroring out - same issue as in https://github.com/mui/mui-toolpad/issues/1855 which is fixed by https://github.com/mui/mui-toolpad/pull/1856, and will be available in the forthcoming release (today).

Till then, I removed the transformation (which you don't actually need since it just returns the data as it is) and your page seems to work:

<img width="909" alt="Screenshot 2023-04-05 at 1 58 13 PM" src="https://user-images.githubusercontent.com/19550456/230210028-c6fac265-3f8a-48d5-add7-2813937ffaec.png">

**Comment by prakhargupta1** [comment]
Hi @Prajapati-developer This has been fixed in the linked PR and is part of Toolpad version v0.1.3.
Can you please check and confirm? Thanks!
