### ISSUE TITLE
Issues faced when copying an app directly to yaml

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1875]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

So, I picked an app from master--toolpad and converted the JSON DOM to yaml. And copied a page to my localhost > toolpad.yaml.  Initially it was a struggle, but later when I understood the indexing and parent, child mapping. It was quick. Some observations:

1. pageRow was not visible on canvas but was there in the yaml. It made it difficult to copy and correctly map the child parent ids, indexing.

2. Page Id is not there in the right panel anymore, had to pick from the URL. Not sure if we removed it in a previous task or is it regression.

3. Order of items (for an element) in master--toolpad was sometimes a bit random. I mean all key:value pairs should follow the same order in all elements. Like 1. id 2. name: 3 type:

**Comment by Janpot** [comment]
Latest version contains PR https://github.com/mui/mui-toolpad/pull/1831 Which should alleviate this process.
After upgrading to this version, your application will be migrated to the new structure where there will be 1 file per page, and the content will be a hierarchical structure that doesn't contain the ids and should be more readable.

To migrate an app from master--toolpad I'd recommend the following:
* create a new empty toolpad app
* remove the toolpad folder, add a toolpad.yml
* copy the app dom from master--toolpad into the toolpad.yml
* run `yarn dev`, it should now create a toolpad folder with pages inside and remove the toopad.yml
* you can now copy pages from this app to other apps

pageRow is not visible in canvas because the this element is managed automatically (i.e. you never have to create, update or remove this element manually).

**Comment by apedroferreira** [comment]
There might be a regression in 1: I have to recheck, but I think that right now it's not possible to hover over the container of the selected element, so I'll still take a look at that.

**Comment by prakhargupta1** [comment]
Update: 1) I just had to manually move the other queries. The pages are working now!

**Comment by Janpot** [comment]
1. I just noticed this as well, just move the `./bundleSizeQueries.ts` file inside of the `resources` folder
2. Looks like we order differently than the file system.

**Comment by Janpot** [comment]
I'm also noticing an issue with the theme: https://tools-public-pr-96.onrender.com/prod/pages/9r8fshsf

**Comment by prakhargupta1** [comment]
Closing it, as the issues are being tackled separately.
