### ISSUE TITLE
Suggestions on improving schema reference page 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2051]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

1. Currently, we show the page with schema content expanded. Collapsing it by default would increase the readability of the doc. Something like:

https://github.com/mui/mui-toolpad/assets/92228082/53c576de-afeb-41ed-9319-5601e5e401a1

2. Currently, there are 2 permalinks. One is for the heading and the other one for the object definition. Should we just make the heading as the only permalink and remove the second one? Video showing both:

https://github.com/mui/mui-toolpad/assets/92228082/31f0743f-1d2b-4952-bc7d-20030aa62ba9

**Comment by Janpot** [comment]
1. It starts expanded because it looks more like how the actual files would look in a code editor and it increases the UX when using the browser _find in page_ function.
2. Deep links are available to improve the shareability of documentation. e.g. to allow us to link to a specific nested property inside of a file.

**Comment by prakhargupta1** [comment]
1. Somehow, I miss going through the content hierarchy on the right side and then I look for a structure in the contents itself.  So, the given the structure is there, let's keep it like this.
2. Ok
