### ISSUE TITLE
Background color of canvas in edit and preview mode is different

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2301]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

#F7F7F7
<img width="847" alt="Screenshot 2023-07-10 at 6 11 39 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/1cc62b84-34bd-4589-9738-97e2c5ac841b">

#FFFFFF
<img width="962" alt="Screenshot 2023-07-10 at 6 11 27 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/f780507b-9ad1-4929-883c-2526bd4c7c91">

### Expected behavior 🤔

Both need to be #FFFFFF
Also, we might need to change the color of side-panels.

Retool and Appsmith keep the background color as light gray both in the Edit and Preview mode.

**Comment by OmPr366** [comment]
@prakhargupta1  can you provide a link?

**Comment by JerryWu1234** [comment]
![image](https://github.com/mui/mui-toolpad/assets/27261522/e74e5f4f-c094-4fa2-ae3e-45afe9f63d07)

because of this property css

**Comment by Janpot** [comment]
Oh, I see, it's the hud applying an overlay even when nothing is selected. We should show the overlay, only when an element is selected

**Comment by Janpot** [comment]
The problem is that these styles:

https://github.com/mui/mui-toolpad/blob/b58d3b1d588bb94173dd2e651fafbacb16f7a066/packages/toolpad-app/src/PinholeOverlay.tsx#L15-L16

also apply on the overlay when nothing is selected:

https://github.com/mui/mui-toolpad/blob/b58d3b1d588bb94173dd2e651fafbacb16f7a066/packages/toolpad-app/src/PinholeOverlay.tsx#L111

Instead we should have these two rules only apply on the divs that appear when something is selected:

https://github.com/mui/mui-toolpad/blob/b58d3b1d588bb94173dd2e651fafbacb16f7a066/packages/toolpad-app/src/PinholeOverlay.tsx#L92-L107

**Comment by JerryWu1234** [comment]
could we give an background color for the preview? 
this way will be easy.

**Comment by JerryWu1234** [comment]
https://github.com/JerryWu1234/mui-toolpad/blob/76473fa2ffe32313c1d62431c92af48d0a1d2726/packages/toolpad-app/src/runtime/ToolpadApp.tsx#L1187

**Comment by Janpot** [comment]
> could we give an background color for the preview?

The background should just follow the background of the theme. This solution won't work in dark mode. The problem lies in the Toolpad editor. You pinpointed the exact location where we need to apply the fix in your comment https://github.com/mui/mui-toolpad/issues/2301#issuecomment-1639755176

**Comment by JerryWu1234** [comment]
thanks I got it
