### ISSUE TITLE
Add Toolpad to the home page of mui.com

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2396]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, we don't show Toolpad when a user scrolls down on the homepage of MUI. We should add it here:

![Screenshot 2023-07-31 at 3 40 39 PM](https://github.com/mui/mui-toolpad/assets/92228082/b0703381-3740-460e-a000-ba943f6d2360)

**Comment by bharatkashyap** [comment]
@prakhargupta1 What do we want to display on the right for Toolpad?

**Comment by prakhargupta1** [comment]
> https://github.com/mui/mui-toolpad/issues/2422

We can show any 1 example from the Toolpad hero section. UI at the top, code at the bottom should fit fine.

**Comment by danilo-leal** [comment]
Yeah, I think the hero section example might be a good one, particularly as we can follow the pattern of "illustrative example/code snippet". Good call with this one! 

Also, just sharing that revamping the home page entirely (to better expose all the products rather than focus primarily on Material UI) is one of my tasks for this semester _still_. So, hoping to collaborate on, potentially, an entire section dedicated to Toolpad in the near future 😬

**Comment by bharatkashyap** [comment]
> Also, just sharing that revamping the home page entirely (to better expose all the products rather than focus primarily on Material UI) is one of my tasks for this semester _still_. So, hoping to collaborate on, potentially, an entire section dedicated to Toolpad in the near future 😬

Excellent to hear! Is it going to be near enough to hold off on this effort, or do we go ahead with this in the meanwhile?

**Comment by bharatkashyap** [comment]
> I think we should probably do this first so the home page revamp doesn't become a blocker! I can kickstart the initial work and then y'all fill in the blanks with the Toolpad demo?!

Sounds great! Thanks 🙏
