### ISSUE TITLE
A new custom component in a new app shows type error in the import statement

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2519]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

<img width="807" alt="Screenshot 2023-08-22 at 1 25 19 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/beeae92c-ffff-4ee7-9ec2-6f287c6cbf2c">

### Your environment 🌎

System:
    OS: macOS 13.3
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Edge: Not Found
    Safari: 16.4
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.11 
    @mui/core-downloads-tracker:  5.14.5 
    @mui/icons-material:  5.14.3 
    @mui/lab:  5.0.0-alpha.140 
    @mui/material:  5.14.5 
    @mui/private-theming:  5.14.5 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.14.5 
    @mui/toolpad: 0.1.24 => 0.1.24 
    @mui/toolpad-components:  0.1.24 
    @mui/toolpad-core:  0.1.24 
    @mui/toolpad-utils:  0.1.24 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.5 
    @mui/x-data-grid:  6.11.1 
    @mui/x-data-grid-pro:  6.11.1 
    @mui/x-date-pickers:  6.11.1 
    @mui/x-date-pickers-pro:  6.11.1 
    @mui/x-license-pro:  6.10.2 
    @types/react:  18.2.20 
    react:  18.2.0 
    react-dom:  18.2.0 
    typescript:  5.1.6

**Comment by Janpot** [comment]
This can be fixed by adding ./toolpad/components/tsconfig.json` with the following content

```json
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "bundler",
    "jsx": "react"
  }
}
```

In the short term we can fix this with https://github.com/mui/mui-toolpad/pull/2522. But this is not a fully satisfying solution. Users may have a `tsconfig.json` higher up in the hierarchy that may influence module resolution inside of the toolpad folder. We could write a `tsconfig.json` with the aforementioned content to the components folder on every server start to make sure modules are resolved as expected in there.
