### ISSUE TITLE
Authorization paid plan error message

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#3181]
### Steps to reproduce

Getting an error message when on a free plan

<img width="356" alt="Screenshot 2024-02-08 at 11 41 14" src="https://github.com/mui/mui-toolpad/assets/2109932/7863c35d-536a-4a4c-aea6-712a1e50a397">

### Expected behavior

Options:
1. No _Authorization_ section visible. 
2. A "pro" badge after Authorization title and a help icon that links to relevant documentation.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: authentication free

**Comment by bharatkashyap** [comment]
### 1. Use a "pro badge" followed by a Help Tooltip, and disable the actual feature:

https://github.com/mui/mui-toolpad/assets/19550456/52100fce-ab5a-4d2e-b453-52644a7100b9


#### Pros
- This helps us standardise an indicator for all potential paid features in the future.
- This also makes the actual feature discoverable (the drop-downs are visible but disabled)


### 2. Modify the existing alert and remove all instances of "error":

![Screenshot 2024-04-04 at 6 21 21 PM](https://github.com/mui/mui-toolpad/assets/19550456/4a7c127f-6e76-4126-9c41-c5bda60e44fa)


#### Pros
- This offers a more discoverable path to upgrading, rather than it being hidden behind a Tooltip
