### ISSUE TITLE
Strange behaviour of onClick navigation prop of a Button

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#3535]
### Steps to reproduce

Video from v0.1.55

https://github.com/mui/mui-toolpad/assets/92228082/94df36ef-c0f0-4139-9c30-a7a5f258d93a

After navigating to another page, on clicking the browser back button:
- the app goes to preview mode.
- and back in the edit mode, the original button disappears.

**Search keywords**: button

**Comment by Janpot** [comment]
Toolpad doesn't create history entries when switching between pages. So when you click the back button after switching a page, it goes back to wherever you were before. If you were on the preview page before, it will go back to that preview. The reason is that since undo/redo also takes into account switching views it gets too close intertwined with the back button. I don't believe we don't have as much control as we want over the history stack to really deal with the hitting corner-cases. So switching pages is a history replace, not a history push. We could make this more intuitive by making the page name a query parameter instead, e.g. `/prod/editor/app?page=myPage`

Regarding the disappearing button, there seems to be going something wrong on your end when saving the project:
![Screenshot 2024-05-21 at 11 40 04](https://github.com/mui/mui-toolpad/assets/2109932/08a806c9-c798-4ff4-bdd2-528024b71cf4)

This is a different issue, if you still experience this, can you create a reproduction and open a new ticket?

**Comment by prakhargupta1** [comment]
Thanks for the elaborate explanation, now I see why is it happening. We can keep it like this for now.

About the error during saving, it is happening only for this app. I took a fresh pull of the repo, closed all node processes, ran tools-public app with `pnpm i` and `pnpm run dev` commands. When I drag a button I see that there is error while saving. I don't know what could be causing this, I also restarted the system.

**Comment by Janpot** [comment]
You're running into this problem: https://github.com/mui/mui-toolpad/pull/3066
To fix this go to the root of `mui-public` and run `yarn`.


For the future, please include an exact reproduction, a video isn't very useful on its own, best to share some code and exact reproduction steps. Help maintainers to reproduce the issue with as little effort as possible.

**Comment by prakhargupta1** [comment]
> To fix this go to the root of mui-public and run yarn.
This worked! Thanks.

I had a hunch that the issue was with my local setup. But I understand sharing a repository link could help isolate the problem for it to be concluded as a local issue.
I am closing this issue for now, we can see if any external user reports the back button problem in the future.
