### ISSUE TITLE
Simplify dev workflow

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#432]
Currently one has to run `yarn dev` some where to build all the projects, and then `yarn cli` to run. We should consider combining the commands and have a single `yarn dev` command start the cli and watch/build all the packages

**Comment by apedroferreira** [comment]
Yes, a single `yarn dev` script to run the app locally should cover all my (very minor) pain points when trying to run the project locally:
- `yarn dev` being a command that builds instead of running the app as is typical/expected in many projects
- `yarn dev` not exiting because it watches for changes in the code, which would not be the intended usage for someone who is just setting up the project to run locally for the first time
- `yarn cli` not being a very explicit name for the command that runs the app
