### ISSUE TITLE
[website] Landing page

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#477]
Build a landing page in mui core repo, similar to MUI X

## Implementation

- [x] Add a redirection rule in https://github.com/mui/material-ui/blob/be24437157376588d5feb17e72dc369c15125669/docs/public/_redirects#L329 like for MUI X to redirect all the traffic of https://mui.com/toolpad to our docs https://github.com/mui/material-ui/pull/33287
- [x] Setup a `/docs` folder in this report on port 3003 (https://www.notion.so/mui-org/Ports-b113d0d4c76c4db9a0ef99c703d0084c)

**Comment by gerdadesign** [comment]
Added some wireframe updates in [figma](https://www.figma.com/file/fNowz3HeGrUJshzjUvvY1e/Toolpad-landing-page?node-id=12%3A150) based on previous iterations + what we've discussed. There is still a lot of copy to be filled in/edited as well as a number of questions I added as sticky notes in the doc.

**Comment by gerdadesign** [comment]
## New version is updated in [figma](https://www.figma.com/file/fNowz3HeGrUJshzjUvvY1e/Toolpad-landing-page?node-id=346%3A6391)!  

- [Features](https://www.notion.so/mui-org/Landing-page-content-304da6c2b5364d4fb14a8d76c7c55a56#76ee21909d3a4fdd9728b2230ec2789d) are added 
- Are these [use cases](https://www.notion.so/mui-org/45b001772b964c1a9df8d99619ec2551?v=22a4c7f6883f4cdf8572271fa0276480&p=3c615981709a4dcb995acf45ad561743) ready to be added or was there more work to be done on this? 
- [Pricing](https://www.notion.so/mui-org/Toolpad-pricing-50df8f336b3d4120b8df8a8cef0b7fa9#b5412fba6de244ffb5e71f694389e072) is added 

## There are a few lingering questions: 
- It still feels like the content itself could use a clean-up — would people brand new to Toolpad understand all the offerings & their choices at this stage? 
- Under pricing, I tried to group items to match the look of our current MUI pricing page. I don't know if the content of these groupings are correct. Some list items seem like they could be consolidated. Since y'all know better, please adjust these to what makes the most sense! 
- We have a number of items on this landing page that are a WIP. I added a singular section to link out to GitHub instead of the many exit points. 
  - Currently I took away the 🚧 marker for all the WIP items since there are so many 
  - Are we planning to have all the features listed live in the beta version? 
- Anywhere you see "lorem ipsum" needs copy; feel free to edit directly in figma!

**Comment by gerdadesign** [comment]
Adding that [this](https://www.figma.com/file/fNowz3HeGrUJshzjUvvY1e/Toolpad-landing-page?node-id=914%3A55924) is now up to date with all available information so far — Pricing, illustrations for use cases, logo. 
Only outstanding pieces are: 

- team review of content 
- copy review from Sam 
- Video (WIP via slack)

**Comment by bharatkashyap** [comment]
@gerdadesign Looks great! I'd need the SVGs of the illustrations for the use-case cards (as well as the logos).

**Comment by prakhargupta1** [comment]
@samuelsycamore When you get time, please review content of the Figma file shared by Gerda.
You can add comments, and we can resolve them there.
Thanks
