### ISSUE TITLE
Component discoverability in catalog

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#598]
Aspects:

* Catalog placement in overall app layout
* Search box to filter
* Organization of components in categories
* Visual cues (icon for each component)

### Benchmarks

* Framer

  <img width="520" alt="Screenshot 2022-05-01 at 18 14 19" src="https://user-images.githubusercontent.com/3165635/166155228-24439d3c-fa77-41db-93e5-e21ee1f7a804.png">

* retool
  ![Screenshot 2022-06-24 at 15 12 34](https://user-images.githubusercontent.com/2109932/175543112-ca884d8c-f4aa-4cd1-8711-ed1b9c995d39.png)

* appsmith
  ![Screenshot 2022-06-24 at 15 13 46](https://user-images.githubusercontent.com/2109932/175543329-55595381-bc88-4427-9f36-e7c4c70d148b.png)

* notion

  ![Screenshot 2022-06-24 at 15 14 18](https://user-images.githubusercontent.com/2109932/175543446-cd678348-3b58-49d1-a1bc-f74288c85d20.png)

* makeswift

  ![Screenshot 2022-06-24 at 15 15 35](https://user-images.githubusercontent.com/2109932/175543663-ea7c437b-bae3-435a-80d5-8e81244bf504.png)

* Flutterflow

  ![Screenshot 2022-06-24 at 15 16 27](https://user-images.githubusercontent.com/2109932/175543895-ba22c146-28ab-4f18-b4a4-e07542d88837.png)

* Jetadmin

  ![Screenshot 2022-06-24 at 15 18 30](https://user-images.githubusercontent.com/2109932/175544143-b4637421-31e0-4a0e-ab79-438c7eb5acf1.png)
 
*

**Comment by prakhargupta1** [comment]
More discussion in: https://github.com/mui/mui-toolpad/issues/344

**Comment by prakhargupta1** [comment]
As discussed yesterday, we can do this separately. @gerdadesign to share component library designs.

**Comment by gerdadesign** [comment]
As discussed, here's a quick screenshot of the component drawer in its current position, but just swapping the layout of the components inside. This _is_ created with some styling exploration for the MUI dark theme in mind, but let me know if anything is unclear in order to move forward with this incremental change. 

<a href="https://www.figma.com/file/14OEUnwh4ahMb2empYAEc8/Toolpad-UX?node-id=278%3A14695">
<img src="https://user-images.githubusercontent.com/106991024/190036588-8320e44a-15ae-4809-8339-7667f94beb99.png" alt="Drawer mockup"></a>

**Comment by prakhargupta1** [comment]
I think we decided to replace upvote icons with the icon illustration. 
We can show the icon near Upvote reference. Like **Upvote :thumbsup: to get it prioritized.**

**Comment by Janpot** [comment]
Shall we change the vertical "Components" text to "Component library" to be more in line with https://github.com/mui/mui-toolpad/issues/878?

**Comment by gerdadesign** [comment]
Updates with the name change & an alternative option for showing the WIP components. 

Personally, I feel like the 👍 icon better connects the people to action we want them to take. In the second version, the instruction is at the top (and requires users to read) instead of visually connected on the button itself. The boxes have to look disabled to show you can't use them, even though they are actually clickable and we _do_ want you to take an action on them. 

<a href="https://www.figma.com/file/14OEUnwh4ahMb2empYAEc8/Toolpad-UX?node-id=278%3A14695"><img src="https://user-images.githubusercontent.com/106991024/190217553-84d8f5c9-0d27-4760-897f-5bd245c004f9.png" alt="Drawer version 2"></a>

**Comment by bharatkashyap** [comment]
> In the second version, the instruction is at the top (and requires users to read) instead of visually connected on the button itself. 

Agreed; however, the second version also requires users to read the name of the component instead of being able to see what component they could get if they upvoted. I would personally feel a sense of "missing out" greater if I saw the icon, which would then prompt me to go and upvote. Seeing an upvote icon might not trigger in me the need to go and upvote at all.

**Comment by prakhargupta1** [comment]
In case 1, I think having many upvote icons draws user attention from the more significant upper section. I would prefer 2nd UI.
