### ISSUE TITLE
Custom components: add a console for debugging

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#663]
Just like in the function query editor, we could add a browser console in the bottom right to help debugging custom components.

<img width="1188" alt="Screenshot 2022-07-19 at 15 07 54" src="https://user-images.githubusercontent.com/2109932/179757844-f0bcf329-1999-49d9-96b2-e664c60d74ba.png">

benchmark:
- [codesandbox](https://codesandbox.io/)

**Comment by bytasv** [comment]
As per initial investigation done in https://github.com/mui/mui-toolpad/pull/711 looks like it's not a straight forward thing to do.
Seems that, we need to refactor current custom component editor so that the code gets evaluated in an isolated iframe context. Once that's done we should be able to hook into `console.*` calls and pass them to our `Console` component.
Let's keep this issue open and decide on a priority among other things for now

**Comment by prakhargupta1** [comment]
I guess we can close this? @Janpot
